"use client";

import { useEffect, useState } from "react";
import {
  Sparkles,
  TrendingUp,
  AlertTriangle,
  Flame,
  CheckCircle,
  RefreshCw,
  Database,
  Loader2,
  Tag,
  ArrowRight,
  Info,
} from "lucide-react";

interface RecurringTheme {
  theme: string;
  description: string;
  evidence: string[];
}

interface IssueItem {
  issue: string;
  evidence: string;
}

interface InsightsData {
  summary: string;
  recurring_themes: RecurringTheme[];
  persistent_issues: IssueItem[];
  emerging_issues: IssueItem[];
  improving_issues: IssueItem[];
}

export default function InsightsPage() {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

  const [insights, setInsights] = useState<InsightsData | null>(null);
  const [memoryCount, setMemoryCount] = useState<number>(0);
  const [isLoading, setIsLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const fetchInsights = async () => {
    setIsLoading(true);
    setErrorMsg(null);
    try {
      const res = await fetch(`${apiUrl}/api/insights`);
      if (!res.ok) {
        throw new Error(`Failed to generate insights (status ${res.status})`);
      }
      const data = await res.json();
      setInsights(data.insights);
      setMemoryCount(data.memory_count || 0);
    } catch (err: any) {
      console.error("Error fetching insights:", err);
      setErrorMsg(err.message || "Failed to synthesize insights from Hindsight memory.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  return (
    <div className="space-y-8">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-6 border-b border-slate-200 dark:border-slate-800">
        <div>
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-lg bg-indigo-50 dark:bg-indigo-950/80 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
              <Sparkles className="w-5 h-5" />
            </div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
              Synthesized Insights & Patterns
            </h1>
          </div>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Grounded synthesis generated by Groq reasoning across persistent Hindsight feedback memories.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 text-xs font-semibold">
            <Database className="w-3.5 h-3.5" />
            <span>{memoryCount} Memories Synthesized</span>
          </div>

          <button
            type="button"
            onClick={fetchInsights}
            disabled={isLoading}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-xs font-semibold text-white shadow-sm transition-colors cursor-pointer disabled:bg-indigo-400"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? "animate-spin" : ""}`} />
            <span>Re-synthesize</span>
          </button>
        </div>
      </div>

      {isLoading ? (
        <div className="py-24 text-center space-y-4">
          <Loader2 className="w-8 h-8 animate-spin mx-auto text-indigo-600" />
          <div className="space-y-1">
            <p className="text-sm font-semibold text-slate-800 dark:text-slate-200">
              Recalling Hindsight memories & running Groq synthesis...
            </p>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Identifying recurring friction, emerging complaints, and improving trends.
            </p>
          </div>
        </div>
      ) : errorMsg ? (
        <div className="p-6 rounded-xl border border-rose-200 dark:border-rose-900/60 bg-rose-50/50 dark:bg-rose-950/30 text-rose-700 dark:text-rose-300 space-y-2">
          <p className="font-semibold text-sm">Failed to generate insights</p>
          <p className="text-xs">{errorMsg}</p>
          <button
            onClick={fetchInsights}
            className="mt-3 px-3 py-1.5 rounded-md bg-rose-600 hover:bg-rose-700 text-white text-xs font-semibold"
          >
            Retry Synthesis
          </button>
        </div>
      ) : !insights ? (
        <div className="py-20 text-center border border-dashed border-slate-200 dark:border-slate-800 rounded-xl p-8">
          <Info className="w-8 h-8 mx-auto text-slate-400 mb-2" />
          <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">
            No memories available for synthesis
          </p>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-sm mx-auto">
            Ingest customer feedback on the Feedback page to generate live thematic patterns.
          </p>
        </div>
      ) : (
        <div className="space-y-8">
          {/* Overall Synthesis Banner */}
          <div className="rounded-2xl border border-indigo-200/80 dark:border-indigo-900/60 bg-gradient-to-br from-indigo-50/70 via-white to-purple-50/40 dark:from-indigo-950/40 dark:via-slate-900 dark:to-purple-950/30 p-6 sm:p-8 shadow-sm">
            <div className="flex items-center gap-2 text-indigo-700 dark:text-indigo-400 text-xs font-bold uppercase tracking-wider mb-2">
              <Sparkles className="w-4 h-4" />
              Executive Synthesis
            </div>
            <p className="text-base sm:text-lg text-slate-900 dark:text-slate-100 font-medium leading-relaxed">
              {insights.summary}
            </p>
          </div>

          {/* Recurring Themes Grid */}
          <div>
            <h2 className="text-base font-bold text-slate-900 dark:text-white mb-4 flex items-center gap-2">
              <TrendingUp className="w-4.5 h-4.5 text-indigo-600 dark:text-indigo-400" />
              Recurring Thematic Clusters
            </h2>

            {insights.recurring_themes?.length === 0 ? (
              <p className="text-xs text-slate-500 dark:text-slate-400 italic">
                No distinct recurring clusters identified yet.
              </p>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                {insights.recurring_themes.map((themeItem, idx) => (
                  <div
                    key={idx}
                    className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 shadow-sm hover:border-indigo-300 dark:hover:border-indigo-700 transition-all flex flex-col justify-between"
                  >
                    <div>
                      <div className="flex items-center gap-2 mb-2">
                        <span className="px-2.5 py-1 rounded-md bg-indigo-50 dark:bg-indigo-950/80 text-indigo-700 dark:text-indigo-300 font-semibold text-xs border border-indigo-200/60 dark:border-indigo-800">
                          {themeItem.theme}
                        </span>
                      </div>
                      <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 mt-2 leading-relaxed">
                        {themeItem.description}
                      </p>
                    </div>

                    {themeItem.evidence && themeItem.evidence.length > 0 && (
                      <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800/80 space-y-1.5">
                        <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                          Supporting Evidence:
                        </p>
                        <div className="space-y-1">
                          {themeItem.evidence.map((ev, evIdx) => (
                            <div
                              key={evIdx}
                              className="text-[11px] text-slate-500 dark:text-slate-400 italic bg-slate-50 dark:bg-slate-800/60 px-2 py-1 rounded border border-slate-100 dark:border-slate-800"
                            >
                              &ldquo;{ev}&rdquo;
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Three Categories: Persistent, Emerging, Improving */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Persistent Issues */}
            <div className="rounded-xl border border-rose-200/70 dark:border-rose-900/50 bg-white dark:bg-slate-900 p-5 shadow-sm space-y-3">
              <div className="flex items-center gap-2 text-rose-700 dark:text-rose-400 font-bold text-sm">
                <AlertTriangle className="w-4 h-4" />
                <span>Persistent Friction</span>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Long-standing complaints repeatedly recalled from historical memory.
              </p>

              {insights.persistent_issues?.length === 0 ? (
                <p className="text-xs text-slate-400 dark:text-slate-500 italic py-4">
                  No persistent issues detected.
                </p>
              ) : (
                <div className="space-y-3 pt-2">
                  {insights.persistent_issues.map((item, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-lg bg-rose-50/50 dark:bg-rose-950/30 border border-rose-100 dark:border-rose-900/40 space-y-1.5"
                    >
                      <p className="text-xs font-semibold text-rose-900 dark:text-rose-200">
                        {item.issue}
                      </p>
                      <p className="text-[11px] text-slate-600 dark:text-slate-400 italic">
                        &ldquo;{item.evidence}&rdquo;
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Emerging Issues */}
            <div className="rounded-xl border border-amber-200/70 dark:border-amber-900/50 bg-white dark:bg-slate-900 p-5 shadow-sm space-y-3">
              <div className="flex items-center gap-2 text-amber-700 dark:text-amber-400 font-bold text-sm">
                <Flame className="w-4 h-4" />
                <span>Emerging Friction</span>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                New patterns appearing in recent feedback cohorts.
              </p>

              {insights.emerging_issues?.length === 0 ? (
                <p className="text-xs text-slate-400 dark:text-slate-500 italic py-4">
                  No emerging issues detected.
                </p>
              ) : (
                <div className="space-y-3 pt-2">
                  {insights.emerging_issues.map((item, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-lg bg-amber-50/50 dark:bg-amber-950/30 border border-amber-100 dark:border-amber-900/40 space-y-1.5"
                    >
                      <p className="text-xs font-semibold text-amber-900 dark:text-amber-200">
                        {item.issue}
                      </p>
                      <p className="text-[11px] text-slate-600 dark:text-slate-400 italic">
                        &ldquo;{item.evidence}&rdquo;
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Improving Issues */}
            <div className="rounded-xl border border-emerald-200/70 dark:border-emerald-900/50 bg-white dark:bg-slate-900 p-5 shadow-sm space-y-3">
              <div className="flex items-center gap-2 text-emerald-700 dark:text-emerald-400 font-bold text-sm">
                <CheckCircle className="w-4 h-4" />
                <span>Improving & Resolved</span>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Friction points reported as positive or relieved after changes.
              </p>

              {insights.improving_issues?.length === 0 ? (
                <p className="text-xs text-slate-400 dark:text-slate-500 italic py-4">
                  No improving issues identified yet.
                </p>
              ) : (
                <div className="space-y-3 pt-2">
                  {insights.improving_issues.map((item, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-lg bg-emerald-50/50 dark:bg-emerald-950/30 border border-emerald-100 dark:border-emerald-900/40 space-y-1.5"
                    >
                      <p className="text-xs font-semibold text-emerald-900 dark:text-emerald-200">
                        {item.issue}
                      </p>
                      <p className="text-[11px] text-slate-600 dark:text-slate-400 italic">
                        &ldquo;{item.evidence}&rdquo;
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
